# **💥Numpy💥**

#### This is the most used Python libraries for data science. NumPy consists of a powerful data structure called multidimensional arrays. Pandas is another powerful Python library that provides fast and easy data analysis platform.

#### NumPy is a library written for scientific computing and data analysis. It stands for numerical python and also known as array oriented computing.

#### The most basic object in NumPy is the ndarray, or simply an array which is an n-dimensional, homogeneous array. By homogenous, we mean that all the elements in a NumPy array have to be of the same data type, which is commonly numeric (float or integer).


 ## Why Numpy?
 #### Speed (so fast) and convenient
 
 #### Numpy is much faster than the standard python ways to do computations.
 
#### Vectorised code typically does not contain explicit looping and indexing etc. (all of this happens behind the scenes, in precompiled C-code), and thus it is much more concise.

#### Also, many Numpy operations are implemented in C which is basically being executed behind the scenes, avoiding the general cost of loops in Python, pointer indirection and per-element dynamic type checking. The speed boost depends on which operations you're performing.
 
#### NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists

### Firstly we will import the library (numpy) by this command

In [1]:
import numpy

### Making a numpy array by passing a list 

In [2]:
numpy.array([1,2,3])

array([1, 2, 3])

In [3]:
import numpy as np

### Using alias for numpy


In [4]:
a = np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

### numpy array using list of list (2d)

In [6]:
b = np.array([[1,2,3],[4,5,6]])

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6]])

### for getting the shape of our numpy array

In [8]:
b.shape

(2, 3)

In [9]:
a.shape

(3,)

In [10]:
b.dtype

dtype('int64')

### for getting the dimension of our numpy array

In [11]:
b.ndim

2

In [12]:
print(type(a))

<class 'numpy.ndarray'>


In [13]:
print(type(b))

<class 'numpy.ndarray'>


###  The arange() function is used to get evenly spaced values within a given interval. Values are generated within the half-open interval [start, stop]. For integer arguments the function is equivalent to the Python built-in range function, but returns an ndarray rather than a list.

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# **Performance measurement**
### I mentioned that the key advantages of numpy are convenience and speed of computation.

### You'll often work with extremely large datasets, and thus it is important point for you to understand how much computation time (and memory) you can save using numpy, compared to standard python lists.

In [15]:
c = range(10000)
%timeit [i**3 for i in c]

2.82 ms ± 30.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [16]:
c_numpy = np.arange(10000)
%timeit c_numpy**3

24.2 µs ± 192 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### Still not convinced? want to see one more intresting example

In [17]:
l1 = range(10000)
l2 = [i**2 for i in range(10000)]

In [18]:
%timeit list(map(lambda x, y: x*y, l1, l2))

1.11 ms ± 28.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [19]:
a1 = np.array(l1)
b1 = np.array(l2)

In [20]:
%timeit a1*b1

6.05 µs ± 98.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [21]:
a1

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [22]:
a1 * a1

array([       0,        1,        4, ..., 99940009, 99960004, 99980001])

so I can do everything without even writing a loop? yes... ohh wao

# **Creating Numpy array**

### There are multiple ways to create numpy array. Lets walk over them

In [23]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### It will arrange the values in the interval of 2 between 2 and 12

In [24]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

### zeros() function is one of the most significant functions which is used in machine learning programs widely. This function is used to generate an array containing zeros. The numpy. zeros() function provide a new array of given shape and type, which is filled with zeros.

In [25]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Python numpy. ones() function returns a new array of given shape and data type, where the element's value is set to 1. This function is very similar to numpy zeros() function

In [26]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### An array where all elements are equal to zero, except for the k-th diagonal, whose values are equal to one.


In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### full() function is used to return a new array of a given shape and data type filled with fill_value 

In [28]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [29]:
np.full((3,3),2.2, dtype= np.int)

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

### diag() function. The diag() function is used to extract a diagonal or construct a diagonal array.

In [30]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [31]:
v = np.array([1,2,3])
np.tile(v,(3,1)) # stack 3 copies of v on top of each other

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

### Python Random module is an in-built module of Python which is used to generate random numbers. These are pseudo-random numbers means these are not truly random. This module can be used to perform random actions such as generating random numbers, print random a value for a list or string, etc.


In [32]:

# between 0 and 1
np.random.random()

0.5777658619963024

In [33]:
# so let say I want a random value between 2 and 50
50*np.random.random()+2

12.526618683771444

In [34]:
np.random.random([3,3])

array([[0.05747509, 0.99068139, 0.85679181],
       [0.79417356, 0.00278866, 0.89254655],
       [0.85632188, 0.46626774, 0.4082704 ]])

In [35]:
# 100 values between 1 and 50
a = np.linspace(1,50,100)

In [36]:
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [37]:
#memory used by each array element in bytes
a.itemsize

8

In [38]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### getting 18 equaly spaced number and then reshaping the araay in (2,3,3) shape

In [39]:
np.arange(18).reshape(2,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [40]:
# -1 will automatically adjust dimention
np.arange(18).reshape(2,3,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

# **Accessing Numpy array element**

In [41]:
a = np.array([2,4,6,8,10,12,14,16])

In [42]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### by providing [2] we will access to 3rd element of our numpy array as the index number starts from 0 goes till n-1

In [43]:
a[2]

6

### accessing the 3rd 5th and 7th element of the array

In [44]:
a[[2,4,6]]

array([ 6, 10, 14])

In [45]:
a[2:]

array([ 6,  8, 10, 12, 14, 16])

### [2:5] will include index number 2 but not the 5 so only 3rd 4th 5th element will we taken out

In [46]:
a[2:5]

array([ 6,  8, 10])

### from index 0 to n-1 all the alternate element will be taken out 

In [47]:
a[0::2]

array([ 2,  6, 10, 14])

Lets check the same for 2 D array

In [48]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [49]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
a[2,2]

9

In [51]:
a > 2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [52]:
a[a > 2]

array([3, 4, 5, 6, 7, 8, 9])

In [53]:
a[(a > 2) & (a < 5)]

array([3, 4])

# **Subset of numpy array**

In [54]:
a = np.arange(10)

In [55]:
b = a

In [56]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
b[0] = 11

In [58]:
b

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [59]:
# Notice a is also changed
a

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [60]:
np.shares_memory(a,b)

True

In [61]:
a = np.arange(10)

In [62]:
b = a.copy()

In [63]:
b[0] = 11

In [64]:
b



array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [65]:
np.shares_memory(a,b)

False

In [66]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# **More operations**

In [67]:
a = np.array([[1,2,3],[4,5,6]])

In [68]:
a


array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [70]:
b = np.array([[7,8,9],[10,11,12]])

In [71]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [73]:
a == b

array([[False, False, False],
       [False, False, False]])

In [74]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [75]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# **Mathmatical operation on numpy array**

In [76]:
a = np.arange(1,10)

In [77]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [78]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [79]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [80]:
np.sum(a)

45

In [81]:
np.median(a)

5.0

In [82]:
a.std()

2.581988897471611

In [83]:
a = np.arange(1,10).reshape(3,3)

In [84]:
np.linalg.det(a)

0.0

In [85]:
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [86]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
b = a.T

In [88]:
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [89]:
np.dot(a,b)


array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [90]:
a = np.array([1,1,0], dtype = bool)
b = np.array([1,0,1], dtype = bool)


In [91]:
np.logical_or(a,b)

array([ True,  True,  True])

In [92]:
np.logical_and(a,b)

array([ True, False, False])

In [93]:
np.all(a == a)

True

In [94]:
a = np.array([[1,2],[3,4]])

In [95]:
a


array([[1, 2],
       [3, 4]])

In [96]:
a.sum()

10

In [97]:
a.sum(axis=0)

array([4, 6])

In [98]:
a.sum(axis=1)

array([3, 7])

In [99]:
a.max()

4

In [100]:
a.argmax()

3

In [101]:
a

array([[1, 2],
       [3, 4]])

In [102]:
a.shape

(2, 2)

In [103]:
a[:,np.newaxis].shape # adds a new axis -> 2D

(2, 1, 2)

In [104]:
np.sort(a)

array([[1, 2],
       [3, 4]])

In [105]:
np.argsort(a)

array([[0, 1],
       [0, 1]])

#### **Thank you so much for reading this notebook HOPE YOU LIKED IT**
### **PLEASE UPVOTE and Follow as I am going to upload my complete Machine learning and Deep learning codes**
